name: Deploy Astro to GitHub Pages

on:
  # Activar el despliegue a GitHub Pages solo en la rama release
  push:
    branches: [ release ]
  # Permite correr este flujo de trabajo manualmente desde la pestaña Actions
  workflow_dispatch:

# Dar permisos a GITHUB_TOKEN para publicar
permissions:
  contents: write

# Permite que un despliegue cancele uno anterior que esté en progreso
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  DEPLOY_TARGET: 'pages'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de tu código
        uses: actions/checkout@v4
      
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Instalar dependencias
        run: npm ci

      - name: Construir proyecto en Astro
        run: npm run build

      - name: Prevenir proceso de Jekyll
        run: touch ./dist/.nojekyll

      - name: Desplegar a la rama gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
