name: Deploy to GitHub Pages

on:
  # Activar el despliegue a GitHub Pages solo en la rama release
  push:
    branches: [ release ]
  # Permite correr este flujo de trabajo manualmente desde la pestaña Actions
  workflow_dispatch:

# Dar permisos a GITHUB_TOKEN para publicar en Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite que un despliegue cancele uno anterior que esté en progreso
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de tu código
        uses: actions/checkout@v4
      
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Instalar dependencias
        run: npm ci

      - name: Construir proyecto en Astro
        run: npm run build

      - name: Subir artefacto para Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
